### ISSUE TITLE
Integration with other LSP client 

### ISSUE THREAD

**Issue by bajrangCoder** [salihdhaifullah/cspell-lsp#1]
I am developing a CSpell extension for the Zed code editor by modifying the official VS Code CSpell plugin. However, I encountered some limitations with that plugin. While searching on npmjs, I found this project.

Initially, when I tried it, the setup failed. After reviewing the source code, I managed to get it working by passing a hard-coded location for the home directory during the initialization of the language server. Now, the LSP (Language Server Protocol) starts and runs successfully. 

However, when it comes to spell checking, it fails, and I receive the following error:

```jsonc
// Receive:
{"jsonrpc":"2.0","id":2,"error":{"code":-32603,"message":"Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading 'data')"}}
```

Can you help me resolve this issue? I have no prior experience working with language servers.

**Comment by salihdhaifullah** [comment]
Thanks for reporting the issue @bajrangCoder can you show me the client configuration that you used

**Comment by bajrangCoder** [comment]
It's pretty simple. This is the command used to start the language server:

```rust
pub fn language_server_command(
        &mut self,
        language_server_id: &LanguageServerId,
        worktree: &zed::Worktree,
    ) -> Result<zed::Command> {
        let server_path = self.server_script_path(language_server_id)?;
        Ok(zed::Command {
            command: zed::node_binary_path()?,
            args: vec![
                env::current_dir()
                    .unwrap()
                    .join(&server_path)
                    .to_string_lossy()
                    .to_string(),
                "--stdio".to_string(),
            ],
            env: Default::default(),
        })
    }
```

**Note:** server_path is pointing to cspell-lsp/dist/server.js

And this is what I'm sending on initialisation:

```rust
fn language_server_initialization_options(
        &mut self,
        _: &zed::LanguageServerId,
        _: &zed::Worktree,
    ) -> Result<Option<serde_json::Value>> {
        Ok(Some(serde_json::json!({
            "home": "path to my current opened folder",
        })))
    }
```

**Comment by salihdhaifullah** [comment]
looking at zed it dose not support [pull diagnostics](https://github.com/zed-industries/zed/issues/13107)

**Comment by bajrangCoder** [comment]
Ok got it
