### ISSUE TITLE
Is there a default dictionary for spell checking?

### ISSUE THREAD

**Issue by xulongwu4** [salihdhaifullah/cspell-lsp#7]
Hi, I am trying to set up this lsp to do spell checking, but I see a lot of false positives with the default configuration. Do we have to download a dictionary somewhere or set up one by ourselves? Thanks for your help!

![image](https://github.com/user-attachments/assets/b2bfe69f-f455-457d-8d0b-ea10482bdcce)

**Comment by salihdhaifullah** [comment]
Thank you for bringing this up! It turns out `cspell-lib` relies on `@cspell/cspell-bundled-dicts` for dictionaries. I missed this because I already had the package installed globally.

To fix the issue, you can install the package with:
```bash
pnpm install -g @cspell/cspell-bundled-dicts
```
This should resolve the dictionary-related problems.

**Comment by xulongwu4** [comment]
@salihdhaifullah Thanks a lot. I used the `npm` command to install `cspell-lsp-wrapper` so I changed your instruction to use `npm` instead of `pnpm`, and that fixed my problem!

I will close the issue now, and hopefully the fix will be included in the repo soon. Thanks again!
